name       : tomcat-connectors
version    : 1.2.46
release    : 3
source     :
    - https://github.com/apache/tomcat-connectors/archive/JK_1_2_46.tar.gz : 6bed89609cf4412ffe96f8b325ed76d415cefb309eaf561b214149aea193195b
license    : Apache-2.0
component  : programming
summary    : Provides mod_jk for connecting httpd to a Tomcat container
description: |
    mod_jk is an Apache module used to connect the Tomcat servlet container with web servers such as Apache, iPlanet, Sun ONE (formerly Netscape) and even IIS using the Apache JServ Protocol.
builddeps  :
    - pkgconfig(apr-1)
    - pkgconfig(apr-util-1)
    - pkgconfig(valgrind)
    - httpd-devel
rundeps    :
    - httpd
setup      : |
    cd native
    %reconfigure --with-apxs
build      : |
    cd native
    %make
install    : |
    cd native
    # Install routine is totally broken
    install -D -m 00755 apache-2.0/mod_jk.so $installdir/%libdir%/httpd/mod_jk.so
