name       : tomcat-connectors
version    : 1.2.43
release    : 2
source     :
    - http://www-us.apache.org/dist/tomcat/tomcat-connectors/jk/tomcat-connectors-1.2.43-src.tar.gz : 2ebeba53d26b3a82fca277082c3a3ffd1f67a2b2970d3a4dfcbf0c5dd5b8e671
license    : Apache-2.0
component  : programming
summary    : Provides mod_jk for connecting httpd to a Tomcat container
description: |
    mod_jk is an Apache module used to connect the Tomcat servlet container with web servers such as Apache, iPlanet, Sun ONE (formerly Netscape) and even IIS using the Apache JServ Protocol.
builddeps  :
    - pkgconfig(apr-1)
    - pkgconfig(apr-util-1)
    - pkgconfig(valgrind)
    - httpd-devel
rundeps    :
    - httpd
setup      : |
    cd native
    %configure --with-apxs
build      : |
    cd native
    %make
install    : |
    cd native
    # Install routine is totally broken
    install -D -m 00755 apache-2.0/mod_jk.so $installdir/%libdir%/httpd/mod_jk.so
