name       : tomcat-connectors
version    : 1.2.42
release    : 1
source     :
    - http://ftp.heanet.ie/mirrors/www.apache.org/dist/tomcat/tomcat-connectors/jk/tomcat-connectors-1.2.42-src.tar.gz : ea119f234c716649d4e7d4abd428852185b6b23a9205655e45554b88f01f3e31
license    : Apache-2.0
component  : programming
summary    : Provides mod_jk for connecting httpd to a Tomcat container
description: |
    mod_jk is an Apache module used to connect the Tomcat servlet container with web servers such as Apache, iPlanet, Sun ONE (formerly Netscape) and even IIS using the Apache JServ Protocol.
builddeps  :
    - pkgconfig(apr-1)
    - pkgconfig(apr-util-1)
    - pkgconfig(valgrind)
    - httpd-devel
rundeps    :
    - httpd
setup      : |
    cd native
    %configure --with-apxs
build      : |
    cd native
    %make
install    : |
    cd native
    # Install routine is totally broken
    install -D -m 00755 apache-2.0/mod_jk.so $installdir/%libdir%/httpd/mod_jk.so
